[package]
edition = "2021"
name = "file_service"
version = "0.0.0"

[lib]
crate-type = ["cdylib"]

[features]
default = ["windows-subsystem"]
windows-subsystem = []
debugfile = []

[dependencies]
# disable openssl!! we do not do any internet things here
git2 = { version = "0.19.0", default-features = false }
# Default enable napi4 feature, see https://nodejs.org/api/n-api.html#node-api-version-matrix
napi = { version = "2.12.2", default-features = false, features = [
  "napi4",
  "async",
  "tokio_rt",
] }
napi-derive = "2.12.2"
tokio = { version = "1.32.0", features = ["process", "full"] }
sha2 = "0.10.7"
rand = "0.8.5"
tempfile = "3.8.0"
anyhow = "1.0.75"
tonic = "0.9.2"
prost = "0.11.9"
dunce = "1.0.1"
ignore = "0.4.20"
encoding_rs = "0.8.33"
futures = "0.3.28"
dissimilar = "1.0.7"
serde = "1.0.95"
serde_derive = "1.0.95"
serde_json = "1.0.95"
log = "0.4.22"

[build-dependencies]
napi-build = "2.0.1"
tonic-build = "0.9.2"
anyhow = "1.0.75"
glob = "0.3.0"


[profile.release]
lto = true
